[pytest]
addopts = --asyncio-mode=auto --maxfail=1 --cov=backend/server -m "not perfs and not match" -x --ignore=backend/tsts_old
testpaths = backend/tests
norecursedirs = backend/tsts_old
log_cli_level = INFO
markers =
    perfs: performance tests that are not run by default
    match: tests which ensure backward-compatibility with kimina-lean-server
